server:
  port: 3004

spring:
  application:
    name: tao-service
org:
  neo4j:
    driver:
      uri: neo4j+s://52667faa.databases.neo4j.io
      authentication:
        username: neo4j
        password: SsoBFsrhUtpHmyTV3S3Kzlr5INjIIqVwzakTOrCgu_k
      config:
        encrypted: true

security:
  basic:
    enable: false

  jwt:
    uri: /auth/**
    header: Authorization
    prefix: Bearer
    expiration: 86400
    secret: JwtSecretKey